name: ğŸ¤– merge

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'distantcam/autoctor'
    steps:
      - name: ğŸ“¡ Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
      - name: âœ”ï¸ Merge PR
        if: |
          steps.dependabot-metadata.outputs.dependency-group == 'tunit'
          && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
