name: âœï¸ pr

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  test:
    name: ğŸ§ª Run tests
    uses: ./.github/workflows/test.yml

  merge:
    name: ğŸ¤– Merge
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.event_name == 'pull_request'
      && github.event.pull_request.user.login == 'dependabot[bot]'
      && github.repository == 'distantcam/autoctor'
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: ğŸ“¡ Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2

      - name: âœ”ï¸ Merge PR
        if: |
          steps.dependabot-metadata.outputs.dependency-group == 'tunit'
          && steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
